# Site settings
title: Rune Framework
description: > # this means to ignore newlines until "baseurl:"
  Rails like framework for node.js
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: /:year/:month/:day/:title
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: RuneFramework
github_username:  runejs

# Build settings
markdown: kramdown
